# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speaker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speaker.proto',
  package='tts',
  syntax='proto2',
  serialized_pb=_b('\n\rspeaker.proto\x12\x03tts\"\'\n\x07Speaker\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06gender\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPEAKER = _descriptor.Descriptor(
  name='Speaker',
  full_name='tts.Speaker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tts.Speaker.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='tts.Speaker.gender', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['Speaker'] = _SPEAKER

Speaker = _reflection.GeneratedProtocolMessageType('Speaker', (_message.Message,), dict(
  DESCRIPTOR = _SPEAKER,
  __module__ = 'speaker_pb2'
  # @@protoc_insertion_point(class_scope:tts.Speaker)
  ))
_sym_db.RegisterMessage(Speaker)


# @@protoc_insertion_point(module_scope)
