# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tts.proto',
  package='tts',
  syntax='proto2',
  serialized_pb=_b('\n\ttts.proto\x12\x03tts\"\"\n\tUtterance\x12\x15\n\x01\x61\x18\x01 \x02(\x0b\x32\n.tts.msg_a\"\x1e\n\x05msg_a\x12\x15\n\x01\x62\x18\x01 \x02(\x0b\x32\n.tts.msg_b\"6\n\x05msg_b\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\x1f\n\x06params\x18\x14 \x02(\x0b\x32\x0f.tts.msg_params\"*\n\nmsg_params\x12\r\n\x05pitch\x18\x02 \x02(\x02\x12\r\n\x05speed\x18\x03 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UTTERANCE = _descriptor.Descriptor(
  name='Utterance',
  full_name='tts.Utterance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='tts.Utterance.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=52,
)


_MSG_A = _descriptor.Descriptor(
  name='msg_a',
  full_name='tts.msg_a',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='tts.msg_a.b', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=84,
)


_MSG_B = _descriptor.Descriptor(
  name='msg_b',
  full_name='tts.msg_b',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='tts.msg_b.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='tts.msg_b.params', index=1,
      number=20, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=140,
)


_MSG_PARAMS = _descriptor.Descriptor(
  name='msg_params',
  full_name='tts.msg_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitch', full_name='tts.msg_params.pitch', index=0,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='tts.msg_params.speed', index=1,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=184,
)

_UTTERANCE.fields_by_name['a'].message_type = _MSG_A
_MSG_A.fields_by_name['b'].message_type = _MSG_B
_MSG_B.fields_by_name['params'].message_type = _MSG_PARAMS
DESCRIPTOR.message_types_by_name['Utterance'] = _UTTERANCE
DESCRIPTOR.message_types_by_name['msg_a'] = _MSG_A
DESCRIPTOR.message_types_by_name['msg_b'] = _MSG_B
DESCRIPTOR.message_types_by_name['msg_params'] = _MSG_PARAMS

Utterance = _reflection.GeneratedProtocolMessageType('Utterance', (_message.Message,), dict(
  DESCRIPTOR = _UTTERANCE,
  __module__ = 'tts_pb2'
  # @@protoc_insertion_point(class_scope:tts.Utterance)
  ))
_sym_db.RegisterMessage(Utterance)

msg_a = _reflection.GeneratedProtocolMessageType('msg_a', (_message.Message,), dict(
  DESCRIPTOR = _MSG_A,
  __module__ = 'tts_pb2'
  # @@protoc_insertion_point(class_scope:tts.msg_a)
  ))
_sym_db.RegisterMessage(msg_a)

msg_b = _reflection.GeneratedProtocolMessageType('msg_b', (_message.Message,), dict(
  DESCRIPTOR = _MSG_B,
  __module__ = 'tts_pb2'
  # @@protoc_insertion_point(class_scope:tts.msg_b)
  ))
_sym_db.RegisterMessage(msg_b)

msg_params = _reflection.GeneratedProtocolMessageType('msg_params', (_message.Message,), dict(
  DESCRIPTOR = _MSG_PARAMS,
  __module__ = 'tts_pb2'
  # @@protoc_insertion_point(class_scope:tts.msg_params)
  ))
_sym_db.RegisterMessage(msg_params)


# @@protoc_insertion_point(module_scope)
